services:
  autolongfor:
    image: crpi-9tzyvu07uw73gfd7.cn-hangzhou.personal.cr.aliyuncs.com/cvjunior2023/autolongfor:main
    container_name: autolongfor
    restart: "no"
    volumes:
      - ./data:/data
      - ./lhtj_data.json:/app/lhtj_data.json
    environment:
      - FSKEY=${FSKEY}
      TZ: Asia/Shanghai
